
version: "3.8"

services:
  owasp-zap-0:
    image: zaproxy/zap-stable
    container_name: zap-stable-0
    restart: unless-stopped
    network_mode: "host"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8090
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config connection.timeoutInSecs=300
    volumes:
      - ./volumes/zap0:/zap/results

  owasp-zap-1:
    image: zaproxy/zap-stable
    container_name: zap-stable-1
    restart: unless-stopped
    network_mode: "host"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8091
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config connection.timeoutInSecs=300
    volumes:
      - ./volumes/zap1:/zap/results

  owasp-zap-2:
    image: zaproxy/zap-stable
    container_name: zap-stable-2
    restart: unless-stopped
    network_mode: "host"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8092
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config connection.timeoutInSecs=300
    volumes:
      - ./volumes/zap2:/zap/results